ALTER TABLE teams ADD COLUMN IF NOT EXISTS fallback_config JSONB;
ALTER TABLE request_logs ADD COLUMN IF NOT EXISTS model_used TEXT;
ALTER TABLE request_logs ADD COLUMN IF NOT EXISTS was_fallback BOOLEAN DEFAULT FALSE;
